apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memos
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: |
      tinyauth-tinyauth-redirect@kubernetescrd,
      tinyauth-tinyauth@kubernetescrdspec:
  ingressClassName: traefik
  rules:
  - host: note.juuuwon.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: memos
            port:
              number: 5230